import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// worker-configuration.d.ts is generated by `npm run types` (wrangler types) from
// wrangler.jsonc.example. A hand-edited or stale copy would type bindings the config
// does not declare, or miss ones it does, so the binding names in the two are derived
// and compared in both directions. The count read is asserted so an empty parse cannot
// pass for "they agree".

const TYPES = { d1_databases: "D1Database", kv_namespaces: "KVNamespace", r2_buckets: "R2Bucket" } as const;

function exampleBindings(): Map<string, string> {
  const text = readFileSync(join(ROOT, "wrangler.jsonc.example"), "utf8");
  // Line comments only start a line here; "//" inside a string value (a URL) is kept.
  const json = text.replace(/^\s*\/\/.*$/gm, "");
  const config = JSON.parse(json.replace(/,(\s*[}\]])/g, "$1")) as Record<string, unknown>;
  const found = new Map<string, string>();
  for (const [key, type] of Object.entries(TYPES)) {
    for (const entry of (config[key] ?? []) as Array<{ binding: string }>) found.set(entry.binding, type);
  }
  for (const name of Object.keys((config.vars ?? {}) as object)) found.set(name, "var");
  return found;
}

function generatedBindings(): Map<string, string> {
  const text = readFileSync(join(ROOT, "worker-configuration.d.ts"), "utf8");
  const body = /interface __BaseEnv_Env \{([\s\S]*?)\n\}/.exec(text)?.[1] ?? "";
  const found = new Map<string, string>();
  for (const line of body.split("\n")) {
    const m = /^\s*(\w+): (.+);$/.exec(line);
    if (!m) continue;
    found.set(m[1], Object.values(TYPES).includes(m[2] as never) ? m[2] : "var");
  }
  return found;
}

test("worker-configuration.d.ts declares exactly the bindings and vars wrangler.jsonc.example does", () => {
  const example = exampleBindings();
  const generated = generatedBindings();
  assert.ok(example.size >= 6, `read only ${example.size} bindings from the example`);
  assert.deepEqual([...generated].sort(), [...example].sort(), "run `npm run types` and commit worker-configuration.d.ts");
});
