/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.dryrun.jsonc --include-runtime=false` (hash: b971821b059a30a4b595b5db67963c7e)
interface __BaseEnv_Env {
	APP_KV: KVNamespace;
	OAUTH_KV: KVNamespace;
	MEDIA: R2Bucket;
	HOLDOUT: R2Bucket;
	DB: D1Database;
	GITHUB_APP_CLIENT_ID: "Iv23lik2O8SPPksxbc6O";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_APP_CLIENT_ID">> {}
}
