// Makes the dev fixture typecheck against the contract. A JSON import widens every
// string to `string`, so it cannot be checked against OpsFeed's unions directly;
// this writes the fixture as an `as const` literal with `satisfies`, and the
// `tsc` that follows in `npm run check` fails on any field the contract does not
// have, any missing field, and any value outside its union.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const fixture = fileURLToPath(new URL("../dev/sample-feed.json", import.meta.url));
const outDir = fileURLToPath(new URL("../dev/generated/", import.meta.url));

// A missing or unparsable fixture throws here, and the check fails.
const feed = JSON.parse(readFileSync(fixture, "utf8"));

const ts = `// Generated by scripts/fixture-check.mjs from dev/sample-feed.json. Do not edit.
import type { OpsFeed } from "../../src/types";

type DeepReadonly<T> = T extends ReadonlyArray<infer U>
  ? ReadonlyArray<DeepReadonly<U>>
  : T extends object
    ? { readonly [K in keyof T]: DeepReadonly<T[K]> }
    : T;

export const sampleFeed = ${JSON.stringify(feed, null, 2)} as const satisfies DeepReadonly<OpsFeed>;
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(`${outDir}sample-feed.check.ts`, ts);
console.log("fixture-check: wrote dev/generated/sample-feed.check.ts; tsc checks it against OpsFeed");
